#' \code{getPlotTitle} output a sequence of logarithmically spaced numbers.
#'
#' \code{getPlotTitle} generates plot title for samples
#'
#' @param plotname the path of where the pdf plot result will be stored 
#' which is generated by compute_signatures_for_all_examples funtion in 
#' plotting.R in TrackSig/scr
#' @param to last number in the sequence.
#' @param length.out length of the sequence, a positive integer > 1. Default is 10.
#' @return A string of the tilte of the plots.
#' @seealso \code{\link{compute_signatures_for_all_examples}}
#' @examples
#' plot_name <- "results_signature_trajectories/ALL/sampleId/sampleId.pdf"
#' getPlotTitle(plot_name)
#' @export
getPlotTitle <- function(plot_name){
  titles <- unlist(strsplit(plot_name, "/"))
  title <- titles[length(titles)]
  plotTitle<- unlist(strsplit(plotTitle, "\\."))
  plotTitle <- plotTitle[1]
  
  return(plotTitle)
}

# [END]